---

- name: Ensures {{ destFolder }} dir exists
  file:
    path: "{{ destFolder }}"
    state: directory

- name: Copy files
  copy:
    src: "{{ item }}"
    remote_src: no
    dest: "{{ destFolder }}"
  loop:
    - "chart"

- name: Register deployed count chart
  shell: helm ls | grep {{ releaseName }} | wc -l
  register: deployed

- name: Install kibana
  shell: |
    helm install \
     --name {{ releaseName }} \
     --set elasticsearch.url={{ elasticsearch.url }},ingress.enabled={{ ingress.enabled }},ingress.host={{ ingress.host }} \
     --wait {{ destFolder }}/chart
  when: deployed.stdout == "0"
